spring:
  profiles:
    active: dev
 
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-config-test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/